openapi: 3.0.0
info:
  title: Rust Playground API
  version: 1.0.0
paths:
  /blocks:
    get:
      summary: Get blocks
      description: Retrieve a list of blocks
      responses:
        '200':
          description: A list of blocks
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    block_id:
                      type: string
                      example: 00000000000000000008c14f2c8fbc000d4d1efb1a1c4f7e13e7d233e4513f9b
                    height:
                      type: integer
                      example: 654321
  /addresses:
    get:
      summary: Get addresses
      description: Retrieve a list of addresses
      responses:
        '200':
          description: A list of addresses
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    address:
                      type: string
                      example: addr1q9w7j8c9g8c9g7j8w7j8c9g8c9g7j8c9g8c9g8c9g8c9g8c9g8c9g8c9g8c9g8
                    balance:
                      type: integer
                      example: 1000000
components: {}
