/*
 * Rust Playground API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Address1 {
    /// The unique identifier for the address
    #[serde(rename = "address")]
    pub address: String,
    /// The balance associated with the address
    #[serde(rename = "balance")]
    pub balance: i32,
}

impl Address1 {
    pub fn new(address: String, balance: i32) -> Address1 {
        Address1 { address, balance }
    }
}
