# src/http/paths/blocks.yaml
openapi: 3.0.0
info:
  title: Blocks API
  version: 1.0.0
paths:
  /blocks:
    get:
      summary: Get blocks
      description: Retrieve a list of blocks
      responses:
        '200':
          description: A list of blocks
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    block_id:
                      type: string
                      example: "00000000000000000008c14f2c8fbc000d4d1efb1a1c4f7e13e7d233e4513f9b"
                    height:
                      type: integer
                      example: 654321
    post:
      summary: Store a block
      description: Store a new block in the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                block_id:
                  type: string
                  description: The unique identifier for the block
                  example: 00000000000000000008c14f2c8fbc000d4d1efb1a1c4f7e13e7d233e4513f9b
                height:
                  type: integer
                  description: The height of the block in the blockchain
                  example: 654321
      responses:
        '201':
          description: Block stored successfully